version: '3.4'

services:
  catalogdb:
    image: postgres:17
    volumes:
      - postgres_catalog:/var/lib/postgresql

  basketdb:
    image: postgres:17
    volumes:
      - postgres_basket:/var/lib/postgresql

  distributedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  identitydb:
    image: mcr.microsoft.com/mssql/server

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  orderstream.api:
    image: ${DOCKER_REGISTRY-}orderstreamapi
    build:
      context: .
      dockerfile: Services/Order/OrderStream.Api/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Identity/Identity.Api/Dockerfile

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"

volumes:
  postgres_catalog:
  postgres_basket:
  minio_data:

